import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { cookies } from 'next/headers';
import NavigationBar from "@/components/common/navigation";
import Footer from "@/components/common/footer";
import NotificationComp from "@/components/common/NotificationComp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const msgString: string = cookieStore.get('one_time_msg')?.value || '';

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="w-full box-border flex flex-col">
        {msgString != '' ? <NotificationComp one_time_msg={msgString} /> : null}
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
